# Prometheus configuration for cockroach clusters.
global:
  scrape_interval: 10s
  evaluation_interval: 10s

rule_files:
- "rules/alerts.rules"
- "rules/aggregation.rules"

scrape_configs:
  - job_name: 'cockroach'
    metrics_path: '/_status/vars'
    scheme: 'http'

    tls_config:
      insecure_skip_verify: true

    static_configs:
    - targets: ['db1:8080', 'db2:8080', 'db3:8080']
      labels:
        cluster: 'my-cockroachdb-cluster'
  - job_name: prometheus
    static_configs:
    - targets: ['localhost:9090']
  - job_name: client
    static_configs:
    - targets: ['client:8079']
